// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleManagementSystem.src.Data;

#nullable disable

namespace VehicleManagementSystem.Migrations
{
    [DbContext(typeof(APPCONTEXTDB))]
    [Migration("20260417052659_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleManagementSystem.src.Models.RESERVATIONMODEL", b =>
                {
                    b.Property<int>("reservationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reservationid"));

                    b.Property<DateTime>("duedate")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<DateTime>("reservedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("returneddate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.Property<int>("vehicleid")
                        .HasColumnType("int");

                    b.HasKey("reservationid");

                    b.HasIndex("userid");

                    b.HasIndex("vehicleid");

                    b.ToTable("reservationmodel");
                });

            modelBuilder.Entity("VehicleManagementSystem.src.Models.STAFFMODEL", b =>
                {
                    b.Property<int>("staffid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staffid"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staffid");

                    b.ToTable("staffmodel");
                });

            modelBuilder.Entity("VehicleManagementSystem.src.Models.USERMODEL", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userid"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userid");

                    b.ToTable("usermodel");
                });

            modelBuilder.Entity("VehicleManagementSystem.src.Models.VEHICLEMODEL", b =>
                {
                    b.Property<int>("vehicleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleid"));

                    b.Property<string>("imagelinkplaintext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("licenseplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("vehicleid");

                    b.ToTable("vehiclemodel");
                });

            modelBuilder.Entity("VehicleManagementSystem.src.Models.RESERVATIONMODEL", b =>
                {
                    b.HasOne("VehicleManagementSystem.src.Models.USERMODEL", "user")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleManagementSystem.src.Models.VEHICLEMODEL", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");

                    b.Navigation("vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
